### ISSUE TITLE
Wrong value in metrics.

### ISSUE THREAD

**Issue by zhangzhishan** [ardamavi/Unsupervised-Classification-with-Autoencoder#1]
I added an `metrics=["binary_accuracy"]` in the compile process. However, when train the model, the value of binary_accuracy is always very small. Is there something wrong?

**Comment by ardamavi** [comment]
Which example, file and model?
I try `metrics=["binary_accuracy"]` in MNIST example in `Example of image denoising` model for 3 epoch and `no Data Augmentation` (First Autoencoder example). And result:

```
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 249s - loss: 0.2575 - binary_accuracy: 0.7962 - val_loss: 0.2148 - val_binary_accuracy: 0.7948
```
binary_accuracy: 1 mean it is ok and binary_accuracy: 0 means bad. So it sounds good for Basic Autoencoder with trained with 1 epoch and small dataset(no Data Augmentation).

But If you try the `Unsupervised Classification with Autoencoder` in `Dog-Cat` example. Its normal because models tring finding similarity images in classes.
For example: `Dog-Cat`'s `Unsupervised Classification with Autoencoder` model always trying to decode most similar image for per class. But all images is different(example one class) in this version of project it is so hard and even it is look like impossible for a problem similar to this. Because (in `Dog-Cat` example) cats or dogs not same size and same location in images.

**But** I have just started this project. Now I'm working on the my new algorithm. It makes the project more workable. The new algorithm will change the entire project from the root. The current publications are for open my idea to people and get open source help.
